---
- name: Enable Jenkins Repo
  get_url:
      url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo
- name: Add Jenkins Repo
  shell: "rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key"

- name: install jenkins
  yum: 
     name: jenkins
     state: latest

- name: Start Jenkins
  service: 
       name: jenkins
       enabled: yes
       state: started    
